# Generated by Django 3.2.3 on 2021-06-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
